name: "Keith Pickering Design"
description: "My work portfolio"

url: "https://keithpickering.github.io"

paginate: 8
paginate_path: /projects/page:num
permalink: /:categories/:title
markdown: rdiscount
rdiscount:
    extensions: ['smart']

keep_files: ["css", "js"] 

